version: "3"
services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/db:/data/db

  crudnode:
    container_name: crudnode
    build: .
    image: crudnode
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8000:8000"
